#!/usr/bin/env bash
# OrdexCoin container entrypoint.
#
# Runs the OrdexCoin daemon (ordexcoind) and the OrdexCoin Web UI
# (ordexcoin-web) in a single container. This matches the shape Umbrel
# expects: one app container wrapping both processes (see docs/UMBREL.md).
#
# Environment variables:
#   ORDEXCOIN_DATA     - daemon data directory (default: /data)
#   ORDEXCOIN_RPC_URL  - RPC endpoint the web UI connects to (default: http://127.0.0.1:25173)
#   ORDEXCOIN_P2P_PORT - P2P listen port, must be published on the host for inbound peers
#                        (default: 25174; mainnet default)
#   ORDEXCOIN_WEB_ADDR - web UI listen address (default: 0.0.0.0:3000)
#   ORDEXCOIN_WEB_USER / ORDEXCOIN_WEB_PASS - optional web UI basic auth
#   ORDEXCOIN_UID / ORDEXCOIN_GID - drop to this user inside /data (default
#                                  1000:1000, the umbrelOS app uid/gid)
set -euo pipefail

DATADIR="${ORDEXCOIN_DATA:-/data}"
RPC_URL="${ORDEXCOIN_RPC_URL:-http://127.0.0.1:25173}"
P2P_PORT="${ORDEXCOIN_P2P_PORT:-25174}"
WEB_ADDR="${ORDEXCOIN_WEB_ADDR:-0.0.0.0:3000}"
ORDEXCOIN_UID="${ORDEXCOIN_UID:-1000}"
ORDEXCOIN_GID="${ORDEXCOIN_GID:-1000}"

mkdir -p "$DATADIR"

# Repair the data directory ownership regardless of who created it. A bind or
# volume mount taken from an umbrelOS/root-owned location is not writable by the
# unprivileged runtime user, which previously made the first write below fail
# with "Permission denied". To set ownership we need root, so when the container
# is launched as root (the compose omits `user:`) we fix the mount and then
# re-exec this script as $ORDEXCOIN_UID:$ORDEXCOIN_GID. Running the daemon as a
# non-root user is mandatory (ordexcoind refuses to run as root).
chown -R "$ORDEXCOIN_UID:$ORDEXCOIN_GID" "$DATADIR" || true

if [ "$(id -u)" -eq 0 ]; then
  exec setpriv --reuid="$ORDEXCOIN_UID" --regid="$ORDEXCOIN_GID" \
    --init-groups /usr/local/bin/entrypoint.sh "$@"
fi

CONF="$DATADIR/ordexcoin.conf"

# Generate a minimal config on first run. No rpcuser/rpcpassword is set so the
# daemon writes a .cookie file which ordexcoin-web reads automatically.
if [ ! -f "$CONF" ]; then
  cat > "$CONF" <<EOF
# Generated by the OrdexCoin container entrypoint.
server=1
port=$P2P_PORT
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
# Outbound peer discovery uses the built-in DNS seeds
# (node3.walletbuilders.com, ordexcoinddns.xyz) by default.
# To force a specific peer, add:  addnode=<host>:25174
EOF
  echo "[entrypoint] wrote $CONF"
fi

# Start the daemon unless something is already answering RPC on this datadir
# (e.g. the daemon is managed by a separate container or sidecar).
if ! ordexcoin-cli -datadir="$DATADIR" getblockchaininfo >/dev/null 2>&1; then
  echo "[entrypoint] starting ordexcoind (datadir=$DATADIR)"
  ordexcoind -datadir="$DATADIR" -daemon -pid="$DATADIR/ordexcoind.pid"

  echo -n "[entrypoint] waiting for RPC"
  for _ in $(seq 1 120); do
    if ordexcoin-cli -datadir="$DATADIR" getblockchaininfo >/dev/null 2>&1; then
      echo ""
      echo "[entrypoint] RPC is up"
      break
    fi
    echo -n "."
    sleep 2
  done
else
  echo "[entrypoint] RPC already reachable on $DATADIR"
fi

echo "[entrypoint] starting ordexcoin-web on $WEB_ADDR (rpc=$RPC_URL)"
exec ordexcoin-web \
  -datadir "$DATADIR" \
  -rpc-url "$RPC_URL" \
  -listen "$WEB_ADDR"
